version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD="${PASSWORD_BD}"
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:${PORT_BD}'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_BD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/core
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
